### ISSUE TITLE
comfyui_manager is not recognized

### ISSUE THREAD

**Issue by Lodjuret** [dyscorv/nix-comfyui#5]
To start comfyui i run: nix run github:dyscorv/nix-comfyui#rocm.comfyui-with-extensions

I tried creating a directory called custom_nodes in the directory where i start comfyui from and adding comfyui_manager there but it is not recognized. See nothing in the logs referring to this or see no changes in comfyui.

Any idea how to do this correctly?

**Comment by Nikola-Milovic** [comment]
How did you resolve this?

**Comment by awang9999** [comment]
I'm interested in how you resolved this too.
